-- CREATE TABLE todos
-- (
-- id int auto_increment primary key,
--     title text  NOT NULL,
--     description text NOT NULL,
--     "isFinished" boolean NOT NULL,
--     createdAt datetime,
--     updatedAt datetime
-- )